name: build
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20,50 * * * *'
jobs:
  ui-test:
    environment: test-ui
    runs-on: ubuntu-latest
    env:
      APM_SERVER: "${{ secrets.APM_SERVER }}"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      CI: 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Xvfb for browser tests
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: |
          export DISPLAY=:99
          yarn test
